// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGc0puPjws2pke2cmV4j207BGOalOkYEw',
    appId: '1:663596048557:web:eec9685b6ea24fba1ba624',
    messagingSenderId: '663596048557',
    projectId: 'tomorrow-planter',
    authDomain: 'tomorrow-planter.firebaseapp.com',
    storageBucket: 'tomorrow-planter.firebasestorage.app',
    measurementId: 'G-CXLYYC0JVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHd9XLNdvbRFQddVfJ5xfdT6DKJfhbw40',
    appId: '1:663596048557:android:56586369c8ee21bf1ba624',
    messagingSenderId: '663596048557',
    projectId: 'tomorrow-planter',
    storageBucket: 'tomorrow-planter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpC6F22dYk0OPzcOlU1Ih40N2b6QdZ4A',
    appId: '1:663596048557:ios:680d8164adc040901ba624',
    messagingSenderId: '663596048557',
    projectId: 'tomorrow-planter',
    storageBucket: 'tomorrow-planter.firebasestorage.app',
    iosBundleId: 'com.econanringo.tomorrowPlanter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpC6F22dYk0OPzcOlU1Ih40N2b6QdZ4A',
    appId: '1:663596048557:ios:680d8164adc040901ba624',
    messagingSenderId: '663596048557',
    projectId: 'tomorrow-planter',
    storageBucket: 'tomorrow-planter.firebasestorage.app',
    iosBundleId: 'com.econanringo.tomorrowPlanter',
  );
}
